env: standard
runtime: nodejs16
service: default
handlers:
  # Handle static files.
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
    secure: always
  # Catch all
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
