env: standard
runtime: nodejs19
service: default
instance_class: F1
automatic_scaling:  
  max_instances: 1
handlers:
  # Handle static files.
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
    secure: always
  # Catch all
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
