steps:
  - name: node:19.8.1
    entrypoint: npm
    args: ["clean-install"]
  - name: node:19.8.1
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
